/**
 * PLAN §8.3 — plain-text results summary for the clipboard. Pure & testable;
 * the UI provides already-computed results.
 */

import type { LimitedResult, Machine, Material, Tool } from '../data';
import type { DrillingResult, TurningResult } from '../engine';
import {
  formatResult, formatDrillingResult, formatTurningResult,
  lengthToDisplay, lengthUnit, fmt, type UnitSystem, type Reading,
} from './format';

const line = (label: string, r: Reading) => `${label}: ${r.value} ${r.unit}`;

const FOOTER =
  'Starting points only — verify against tool manufacturer data. Generated by Feeds & Speeds.';

export function millingCopyText(args: {
  limited: LimitedResult;
  material: Material;
  tool: Tool;
  machine: Machine;
  ae_in: number;
  ap_in: number;
  performance: number;
  sys: UnitSystem;
  shareUrl?: string;
}): string {
  const { limited, material, tool, machine, ae_in, ap_in, performance, sys, shareUrl } = args;
  const f = formatResult(limited.result, sys);
  const u = lengthUnit(sys);
  const out = [
    `MILLING — ${material.name}`,
    `Tool: ${tool.name} (Ø${fmt(lengthToDisplay(tool.diameter_in, sys), 3)} ${u}, ${tool.flutes} fl)`,
    `Machine: ${machine.name}`,
    `Cut: WOC ${fmt(lengthToDisplay(ae_in, sys), 3)} ${u} × DOC ${fmt(lengthToDisplay(ap_in, sys), 3)} ${u} @ ${performance}%`,
    '',
    line('RPM', f.rpm),
    line('Feed', f.feed),
    line('Chip load', f.chipload),
    line('SFM', f.sfm),
    line('MRR', f.mrr),
    line('Motor power', f.motorPower),
    line('Deflection', f.deflection),
  ];
  if (limited.clampedRpm || limited.clampedFeed) {
    out.push(`(clamped to machine limits${limited.clampedRpm ? ': rpm' : ''}${limited.clampedFeed ? ' feed' : ''})`);
  }
  out.push('', FOOTER);
  if (shareUrl) out.push(shareUrl);
  return out.join('\n');
}

export function drillingCopyText(args: {
  result: DrillingResult;
  material: Material;
  drillDiameter_in: number;
  drillMaterial: string;
  machine: Machine;
  sys: UnitSystem;
  shareUrl?: string;
}): string {
  const { result, material, drillDiameter_in, drillMaterial, machine, sys, shareUrl } = args;
  const f = formatDrillingResult(result, sys);
  const u = lengthUnit(sys);
  const out = [
    `DRILLING — ${material.name}`,
    `Drill: Ø${fmt(lengthToDisplay(drillDiameter_in, sys), 3)} ${u} ${drillMaterial.toUpperCase()}`,
    `Machine: ${machine.name}`,
    '',
    line('RPM', f.rpm),
    line('Feed', f.feed),
    line('MRR', f.mrr),
    line('Motor power', f.powerAtMotor),
    line('Torque', f.torque),
  ];
  if (f.thrust) out.push(line('Thrust (est. ±50%)', f.thrust));
  out.push(result.peck.note, '', FOOTER);
  if (shareUrl) out.push(shareUrl);
  return out.join('\n');
}

export function turningCopyText(args: {
  result: TurningResult;
  material: Material;
  workpieceDiameter_in: number;
  op: string;
  machine: Machine;
  sys: UnitSystem;
  shareUrl?: string;
}): string {
  const { result, material, workpieceDiameter_in, op, machine, sys, shareUrl } = args;
  const f = formatTurningResult(result, sys);
  const u = lengthUnit(sys);
  const out = [
    `TURNING (${op}) — ${material.name}`,
    `Workpiece: Ø${fmt(lengthToDisplay(workpieceDiameter_in, sys), 3)} ${u}`,
    `Machine: ${machine.name}`,
    '',
    line('RPM', f.rpm),
    line('Feed', f.feed),
    line('Surface speed', f.achievedSfm),
    line('MRR', f.mrr),
    line('Motor power', f.powerAtMotor),
  ];
  if (f.ra) out.push(line('Theoretical finish', f.ra));
  out.push('', FOOTER);
  if (shareUrl) out.push(shareUrl);
  return out.join('\n');
}
